Jdp230201 3
piotr-grosicki/project-jdp-2302-01 pull request #11
Opened 2023-02-04 20:44 UTC by rolandm1

2023-02-05 08:02 UTC, piotr-grosicki requested changes
konflikty

2023-02-05 12:42 UTC, rolandm1 commented
Mam nadzieję że to pomoże nie wiem czemu jakoś dziwnie mi ten pull scalił mi kod.

2023-02-05 19:40 UTC, piotr-grosicki requested changes

2023-02-05 19:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createNewOrder(@RequestBody OrderDto orderDto) {
tutaj by sie przydalo id carta

2023-02-05 19:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void deleteProductFromCart(@RequestBody ProductInCartDto productInCartDto) {
tutaj by sie przydalo id carta

2023-02-05 19:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public ProductInCartDto updateProduct(@RequestBody ProductInCartDto productInCartDto) {
tutaj by sie przydalo id carta

2023-02-05 19:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createCarts(@RequestBody CartsDto cartsDto) {
wszystkie Carts -> Cart, liczba pojedyncza

2023-02-06 19:17 UTC, rolandm1 commented
dobra poprawione czekam na zatwierdzenie

2023-02-07 12:06 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void deleteProductFromCart(@RequestBody ProductInCartDto productInCartDto) {
ale potrzebujemy jeszcze wiedziec ktory produkt nalezy usunac. Ja bym zostawil (@RequestBody ProductInCartDto productInCartDto) z id produktu i id carta

2023-02-07 12:11 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public ProductInCartDto updateProduct(@RequestBody ProductInCartDto productInCartDto) {
Tak jak w poprzednim -  potrzebujemy jeszcze wiedziec ktory produkt nalezy dodac. Ja bym zostawil (@RequestBody ProductInCartDto productInCartDto) z id produktu i id carta

2023-02-07 12:14 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    }
gdzie podajemy jaki produkt ma byc dodany? nie powinno byc @RequestBody

2023-02-07 12:15 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/domain/Carts.java
> +public class Carts {
Cart, liczba pojedyncza?

2023-02-07 12:17 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/domain/ProductInCart.java
> +    private int craftId;
cartId

2023-02-07 12:17 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/domain/ProductInCartDto.java
> +    private int craftId;
cartId

2023-02-07 12:17 UTC, markos02 approved these changes

2023-02-07 16:52 UTC, markos02 requested changes
Wydaje mi sie ze e deleteProduct i updateProduct powinno byc @requestbody ProductInCartDto productInCartDto. Poza tym pare mniejszych komentarzy

2023-02-07 19:12 UTC, rolandm1 commented
Dobra pozmieniałem i jeśli chodzi o te requestBody to w sumie nie jest to wymagane bo jeśli jest użytkownik to będziemy mieć przypisany koszyk do niego więc wewnątrz sobie z tym poradzimy jedyną rzeczą potrzebną będzie produkt który chcemy usunąć lub dodać

2023-02-08 16:18 UTC, markos02 commented
Niby z jednej strony tak, ale nie mieliśmy zrobić tak, że jeden USER moze miec kilka CARTów? Wtedy tzrebaby podac i id produktu i id carta. Ew robimy latwiejsze rowziazanie i 1 USER - 1 CART

2023-02-08 16:18 UTC, markos02 reviewed
Niby z jednej strony tak, ale nie mieliśmy zrobić tak, że jeden USER moze miec kilka CARTów? Wtedy tzrebaby podac i id produktu i id carta. Ew robimy latwiejsze rowziazanie i 1 USER - 1 CART

2023-02-09 12:15 UTC, rolandm1 commented
Też tak myślałem na początku więc jak już podejmować decyzję to jedziemy z @RequestBody. Zobaczcie czy to będzie spoko.

2023-02-09 16:02 UTC, markos02 approved these changes
Wszystko wydaje sie ok!

2023-02-09 16:02 UTC, merged