Jdp230201 21
piotr-grosicki/project-jdp-2302-01 pull request #13
Opened 2023-02-05 16:40 UTC by markos02

2023-02-05 19:40 UTC, piotr-grosicki submitted a review, later dismissed
jedna branch - jedno zadanie, tutaj widze dwa ;)

2023-02-06 09:14 UTC, TomekKowacki commented
Miałem tak samo kiedyś. Trzeba pamiętać żeby przed pobraniem aktualnego repozytorium (git pull) przełączyć się na main lokalnie (git checkout main). W innym wypadku dane są pobierane do branch’a podrzędnego i w momencie tworzenia nowej branch z main wychodzą commity które są już marge.
Przynajmniej tak mi sie wydaje 😁

2023-02-06 17:48 UTC, markos02 commented
Dzieki za poradę, naprawione

2023-02-06 19:12 UTC, TomekKowacki requested changes
Dodał byś jeszcze zależność ManyToMany dla encji Cart i gettery oraz settery?  :)
Po tych działaniach powinno  być OK

2023-02-07 12:43 UTC, markos02 commented
Gettery były - jako adnotacja Lombok :) co do reszty zgoda - poprawione

2023-02-08 16:12 UTC, rolandm1 commented
Nie dopatrzyłem się problemu

2023-02-08 19:11 UTC, TomekKowacki approved these changes

2023-02-08 19:11 UTC, merged