Jdp230201-11
piotr-grosicki/project-jdp-2302-01 pull request #17
Opened 2023-02-06 18:18 UTC by TomekKowacki

Draft dopóki nie będzie encji Cart i User.

2023-02-09 16:09 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
>      private Long id;
Integer

2023-02-09 16:09 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    public boolean isStatus() {
Czemu nazwa metody to isStatus a nie getStatus?

2023-02-09 16:11 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
Trochę się różnią nasze implementacje bo ja uzywam admotacji Lombok @Getter i @Setter a Ty wstawiasz gettery i settery, ale to raczej mała sprawa więc to tylko jako komentarz

2023-02-09 16:12 UTC, markos02 requested changes
Trzy komentarze

2023-02-09 17:36 UTC, TomekKowacki commented
> 

Zmiany zaaplikowane :)

2023-02-09 17:38 UTC, markos02 approved these changes

2023-02-09 17:58 UTC, TomekKowacki commented
konflikty usunięte... teraz tylko marge ;)

2023-02-10 14:19 UTC, rolandm1 approved these changes

2023-02-10 16:49 UTC, markos02 requested changes
Nie mozna zmergowac - nie przechodza testy na CircleCI

2023-02-10 18:17 UTC, markos02 approved these changes

2023-02-10 18:17 UTC, merged