JDP230201-13
piotr-grosicki/project-jdp-2302-01 pull request #18
Opened 2023-02-06 19:30 UTC by TomekKowacki

Wrzucam tutaj do akceptacji bo pomimo błędu jeżeli zostanie dodana branch JDP230201-12 do main to błąd zniknie :)

2023-02-07 12:23 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/repository/GroupProductRepository.java
> +public interface GroupProductRepository extends CrudRepository<GroupProduct, Long> {
Integer?

2023-02-07 12:37 UTC, markos02 requested changes
id nie mialy byc integerami?

2023-02-07 22:07 UTC, rolandm1 requested changes
Drobne zmiany

2023-02-07 22:07 UTC, rolandm1 commented on src/main/java/com/kodilla/ecommercee/domain/GroupProduct.java
> +    public Long getId() {
Tutaj zostawiłeś Long po zmianie na int

2023-02-07 22:07 UTC, rolandm1 commented on src/main/java/com/kodilla/ecommercee/domain/GroupProduct.java
> +    private void setId(Long id) {
Tutaj również Long i int

2023-02-09 16:14 UTC, markos02 approved these changes
Approve

2023-02-09 17:16 UTC, rolandm1 approved these changes
W porządku

2023-02-09 17:42 UTC, markos02 commented
@TomekKowacki u mnie tez testy dla encji Cart nie chcialy przejsc na CircleCI. Musisz miec "w commicie" chociaz wstepna implementacje wszystkich encji z ktorymi masz relacje

2023-02-09 17:56 UTC, merged