JDP230201-22
piotr-grosicki/project-jdp-2302-01 pull request #30
Opened 2023-02-15 19:50 UTC by TomekKowacki

Niby skończone, ale po marge JDP230201-21 może dojść do konfliktów :/

2023-02-15 19:54 UTC, TomekKowacki commented
Jednak nie skończone XD

2023-02-16 17:40 UTC, TomekKowacki commented
- Testy skończone. 
- Konflikty usunięte. 
- Zapraszam do Review :D

2023-02-16 17:47 UTC, markos02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<Object> deleteGroupProduct(@PathVariable Integer groupId) throws GroupNotFoundException {
Do usunięcia? Albo ewentualnie do dodania adnotacja @DeleteMapping :)

2023-02-16 17:51 UTC, markos02 requested changes
Metoda deleteGroupProduct albo do usuniecia (nie ma jej w specyfikacji projektu) albo trzebaby dodac adnotacje @DeleteMapping.
Poza tym wyglada ok :)

2023-02-16 17:55 UTC, TomekKowacki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<Object> deleteGroupProduct(@PathVariable Integer groupId) throws GroupNotFoundException {
Dodam deleteMapping bo trochę słaby by był brak możliwości usunięcia grupy

2023-02-16 18:27 UTC, markos02 approved these changes

2023-02-16 18:57 UTC, rolandm1 approved these changes
Przejrzałem i nie widzę problemów

2023-02-16 18:57 UTC, merged