Jdp230201 4
piotr-grosicki/project-jdp-2302-01 pull request #6
Opened 2023-02-02 15:16 UTC by TomekKowacki

2023-02-02 15:45 UTC, piotr-grosicki requested changes

2023-02-02 15:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public void createOrder(OrderDto orderDto){
brakuje adnotacji RequestBody

2023-02-02 15:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void createProduct(ProductDto productDto){
tutaj tez

2023-02-02 15:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto updateProduct(ProductDto productDto){
i tu

2023-02-02 15:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public OrderDto updateOrder(OrderDto orderDto) {
tutaj tez

2023-02-02 20:40 UTC, piotr-grosicki requested changes
chwila, dlaczego na tej branchy sa dwa controllery? jedna branch -> jedno zadanie

2023-02-03 04:55 UTC, TomekKowacki commented
> chwila, dlaczego na tej branchy sa dwa controllery? jedna branch -> jedno zadanie

Sam bym chciał wiedzieć jak to się stało, ale teraz to nieważne. 
Powiedz mi proszę jak mam to naprawić? 
Da się jakoś wyciągnąć starego commita do nowego brancha?

2023-02-03 08:39 UTC, piotr-grosicki commented
> > chwila, dlaczego na tej branchy sa dwa controllery? jedna branch -> jedno zadanie
> 
> Sam bym chciał wiedzieć jak to się stało, ale teraz to nieważne. Powiedz mi proszę jak mam to naprawić? Da się jakoś wyciągnąć starego commita do nowego brancha?

najlepiej dwie branche nowe zalozyc i uzyc cherrypick https://git-scm.com/docs/git-cherry-pick

2023-02-03 17:31 UTC, closed without merging