JDP230201-2 Adding Product Group endpoints
piotr-grosicki/project-jdp-2302-01 pull request #7
Opened 2023-02-02 20:30 UTC by rolandm1

2023-02-02 20:40 UTC, piotr-grosicki requested changes

2023-02-02 20:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public void createGroup(GroupProductDto groupProductDto) {
requestbody

2023-02-02 20:40 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupProductDto updateProductGroup(GroupProductDto groupProductDto) {
requestbody

2023-02-03 11:07 UTC, rolandm1 commented
Już dodałem proszę o sprawdzenie

2023-02-03 16:04 UTC, merged